const partsData = [
  {
    year: "2011",
    make: "RAM",
    model: "1500",
    productType: "Front Bumper",
    url: "https://partifyusa.com/collections/2011-RAM-1500?filter.p.product_type=Front Bumper",
  },
  {
    year: "2012",
    make: "RAM",
    model: "1500",
    productType: "Front Bumper",
    url: "https://partifyusa.com/collections/2012-RAM-1500?filter.p.product_type=Front Bumper",
  },
  {
    year: "2013",
    make: "RAM",
    model: "1500",
    productType: "Front Bumper",
    url: "https://partifyusa.com/collections/2013-RAM-1500?filter.p.product_type=Front Bumper",
  },
  {
    year: "2014",
    make: "RAM",
    model: "1500",
    productType: "Front Bumper",
    url: "https://partifyusa.com/collections/2014-RAM-1500?filter.p.product_type=Front Bumper",
  },
  {
    year: "2015",
    make: "RAM",
    model: "1500",
    productType: "Front Bumper",
    url: "https://partifyusa.com/collections/2015-RAM-1500?filter.p.product_type=Front Bumper",
  },
  {
    year: "2011",
    make: "RAM",
    model: "1500",
    productType: "Rear Bumper",
    url: "https://partifyusa.com/collections/2011-RAM-1500?filter.p.product_type=Rear Bumper",
  },
  {
    year: "2012",
    make: "RAM",
    model: "1500",
    productType: "Rear Bumper",
    url: "https://partifyusa.com/collections/2012-RAM-1500?filter.p.product_type=Rear Bumper",
  },
  {
    year: "2013",
    make: "RAM",
    model: "1500",
    productType: "Rear Bumper",
    url: "https://partifyusa.com/collections/2013-RAM-1500?filter.p.product_type=Rear Bumper",
  },
  {
    year: "2014",
    make: "RAM",
    model: "1500",
    productType: "Rear Bumper",
    url: "https://partifyusa.com/collections/2014-RAM-1500?filter.p.product_type=Rear Bumper",
  },
  {
    year: "2015",
    make: "RAM",
    model: "1500",
    productType: "Rear Bumper",
    url: "https://partifyusa.com/collections/2015-RAM-1500?filter.p.product_type=Rear Bumper",
  },
  {
    year: "2012",
    make: "RAM",
    model: "2500",
    productType: "Tailgate",
    url: "https://partifyusa.com/collections/2012-RAM-2500?filter.p.product_type=Tailgate",
  },
  {
    year: "2013",
    make: "RAM",
    model: "2500",
    productType: "Tailgate",
    url: "https://partifyusa.com/collections/2013-RAM-2500?filter.p.product_type=Tailgate",
  },
  {
    year: "2014",
    make: "RAM",
    model: "2500",
    productType: "Tailgate",
    url: "https://partifyusa.com/collections/2014-RAM-2500?filter.p.product_type=Tailgate",
  },
  {
    year: "2015",
    make: "RAM",
    model: "2500",
    productType: "Tailgate",
    url: "https://partifyusa.com/collections/2015-RAM-2500?filter.p.product_type=Tailgate",
  },
  {
    year: "2016",
    make: "RAM",
    model: "2500",
    productType: "Tailgate",
    url: "https://partifyusa.com/collections/2016-RAM-2500?filter.p.product_type=Tailgate",
  },
  {
    year: "2013",
    make: "Toyota",
    model: "Camry",
    productType: "Front Bumper",
    url: "https://partifyusa.com/collections/2013-Toyota-Camry?filter.p.product_type=Front Bumper",
  },
  {
    year: "2014",
    make: "Toyota",
    model: "Camry",
    productType: "Front Bumper",
    url: "https://partifyusa.com/collections/2014-Toyota-Camry?filter.p.product_type=Front Bumper",
  },
  {
    year: "2015",
    make: "Toyota",
    model: "Camry",
    productType: "Front Bumper",
    url: "https://partifyusa.com/collections/2015-Toyota-Camry?filter.p.product_type=Front Bumper",
  },
  {
    year: "2016",
    make: "Toyota",
    model: "Camry",
    productType: "Front Bumper",
    url: "https://partifyusa.com/collections/2016-Toyota-Camry?filter.p.product_type=Front Bumper",
  },
  {
    year: "2017",
    make: "Toyota",
    model: "Corolla",
    productType: "Front Bumper",
    url: "https://partifyusa.com/collections/2017-Toyota-Corolla?filter.p.product_type=Front Bumper",
  },
  {
    year: "2013",
    make: "Toyota",
    model: "Corolla",
    productType: "Passenger Side Fender",
    url: "https://partifyusa.com/collections/2013-Toyota-Corolla?filter.p.product_type=Passenger Side Fender",
  },
  {
    year: "2014",
    make: "Toyota",
    model: "Corolla",
    productType: "Passenger Side Fender",
    url: "https://partifyusa.com/collections/2014-Toyota-Corolla?filter.p.product_type=Passenger Side Fender",
  },
  {
    year: "2015",
    make: "Toyota",
    model: "Corolla",
    productType: "Passenger Side Fender",
    url: "https://partifyusa.com/collections/2015-Toyota-Corolla?filter.p.product_type=Passenger Side Fender",
  },
  {
    year: "2016",
    make: "Toyota",
    model: "Corolla",
    productType: "Passenger Side Fender",
    url: "https://partifyusa.com/collections/2016-Toyota-Corolla?filter.p.product_type=Passenger Side Fender",
  },
  {
    year: "2017",
    make: "Toyota",
    model: "Corolla",
    productType: "Passenger Side Fender",
    url: "https://partifyusa.com/collections/2017-Toyota-Corolla?filter.p.product_type=Passenger Side Fender",
  },
];
